### PR TITLE
Python 3 and file name compatibility

### PR DESCRIPTION
**Pull request by captain5050**
Ease working with files. Make a number of the source files python3 compatible. 
Google python style requires files end with .py:
https://google.github.io/styleguide/pyguide.html#3163-file-naming

### CODE REVIEW

**Comment by andikleen** [comment]
Don't you need to fix the shell scripts too for the new names?

**Comment by captain5050** [comment]
> Don't you need to fix the shell scripts too for the new names?

The remaining python scripts need .py adding, adding a .sh to the shell scripts would be nice imo for consistency but is optional in Google style.

**Comment by andikleen** [comment]
I meant the calls to the python files in the shell scripts. Right now they will all fail because they use the old file names

**Comment by captain5050** [comment]
For the renamed files there aren't references from shell scripts, but maybe I'm missing something:

$ grep -l uncore_csv_json *
README.md
uncore_csv_json.py

$ grep -l json-remove-events *
README.md

$ grep -l evj2csv *
README.md

$ grep -l event-oprofile *
event-oprofile.py
README.md

$ grep -l csv-field *
csv-field.py
README.md

$ grep -l json2csv *
README.md

**Comment by andikleen** [comment]
Ok, should be fine then.

**Pull request merged**
